### ISSUE TITLE
Prep for IBC community call

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/apalache-team-services#15]
We should:

- [ ] Get confirmation on attending teams/people (@milosevic)
- [x] Prep slides explaining Quint (@konnov)
- [x] Draft a script for an interactive demo (@bugarela, @thpani)
- [x] Do a test run (Friday?)

Here's a doc with my very rough notes from our meeting last week, please add/change etc. https://docs.google.com/document/d/17Zp253Iy7bHn8P4fJXhYI4vRD4em8cjxCIm872SI1jY/edit

**Comment by bugarela** [comment]
The call was great!
